Sandbox env
hariom61/tf-az-iac pull request #18
Opened 2022-01-06 06:03 UTC by hariom61

2022-01-06 08:05 UTC, dilip-panwar-by requested changes

2022-01-06 08:05 UTC, dilip-panwar-by commented on modules/azure-network-interface/variables.tf
> +  type        = string
why do we need this var?

2022-01-06 08:05 UTC, dilip-panwar-by commented on modules/azure-virtual-network/outputs.tf
> +  value       = azurerm_virtual_network.vnet.name
Please perform `fmt`  before raising a `PR`

2022-01-06 08:05 UTC, dilip-panwar-by commented on modules/azurerm-subnet/outputs.tf
> +output "zurerm-subnet-id" {
typo

2022-01-06 08:05 UTC, dilip-panwar-by commented on modules/random-password/outputs.tf
> +output "zurerm-random-password-result" {
typo

2022-01-06 08:05 UTC, dilip-panwar-by commented on modules/random-password/variables.tf
> +variable "length" {
try to not use reserved words in your defined variables

2022-01-06 12:36 UTC, hariom61 commented on modules/azure-key-vault/variables.tf
> +variable "object_id" {
This variable use in  access_policy  of resource "azurerm_key_vault"

2022-01-06 12:57 UTC, hariom61 commented on modules/random-password/variables.tf
> +variable "length" {
changed, next i'll time remember

2022-01-06 12:57 UTC, hariom61 commented on modules/random-password/outputs.tf
> +output "zurerm-random-password-result" {
done

2022-01-06 12:58 UTC, hariom61 commented on modules/azurerm-subnet/outputs.tf
> +output "zurerm-subnet-id" {
changed

2022-01-06 12:58 UTC, hariom61 commented on modules/azure-virtual-network/outputs.tf
> +  value       = azurerm_virtual_network.vnet.name
done

2022-01-06 12:58 UTC, hariom61 commented on modules/azure-key-vault/variables.tf
> +
Done

2022-01-06 12:58 UTC, hariom61 commented on modules/azure-key-vault/variables.tf
> +variable "enabled_for_disk_encryption" {
Done

2022-01-06 12:58 UTC, hariom61 commented on modules/azure-key-vault/outputs.tf
> +output "zurerm-key-vault-id" {
changed

2022-01-06 14:21 UTC, dilippanwar1 requested changes

2022-01-06 14:21 UTC, dilippanwar1 commented on az-sandbox-env/main.tf
> +module "zurerm-key-vault" {
typo

2022-01-06 14:21 UTC, dilippanwar1 commented on az-sandbox-env/providers.tf
> +    storage_account_name = "storageaccountforenv"
lets have a better storage name as per naming convention

2022-01-06 14:21 UTC, dilippanwar1 commented on az-sandbox-env/providers.tf
> +    container_name       = "storage-sandbox-env"
pls update container_name too

2022-01-08 07:03 UTC, dilip-panwar-by commented on modules/azure-subnet/outputs.tf
> +  description = "azyre subnet id"
Typo in description

2022-01-08 07:03 UTC, dilip-panwar-by commented on modules/azure-virtual-network/outputs.tf
> +  description = "name vartual network"
Typo in description

2022-01-08 07:11 UTC, hariom61 commented on az-sandbox-env/providers.tf
> -  version = "=2.90.0"
because we already provided provider version on _required_providers_

2022-01-08 07:13 UTC, hariom61 commented on .github/workflows/sandbox-tf.yml
> +        uses: dflook/terraform-plan@v1
i'm on it

2022-01-10 07:13 UTC, merged